on:
  push:
    branches:
      - dev
      - master
  pull_request:
    branches:
      - dev

name: dev-check

jobs:
  dev-check:
    runs-on: ${{ matrix.config.os }}
    name: ${{ matrix.config.os }} (${{ matrix.config.r }})
    #if: "!contains(github.event.head_commit.message, 'skip ci')"


    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: windows-latest, r: '4.0'}
          - {os: macOS-latest, r: '4.0'}
          - {os: ubuntu-16.04, r: '4.0', rspm: "https://packagemanager.rstudio.com/cran/__linux__/xenial/latest"}

    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      RSPM: ${{ matrix.config.rspm }}

    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@master
        with:
          r-version: ${{ matrix.config.r }}
      - uses: r-lib/actions/setup-pandoc@master

      - name: Query dependencies
        run: |
          install.packages('remotes')
          saveRDS(remotes::dev_package_deps(dependencies = TRUE), ".github/depends.Rds", version = 2)
          writeLines(sprintf("R-%i.%i", getRversion()$major, getRversion()$minor), ".github/R-version")
        shell: Rscript {0}


      - name: Cache R packages
        if: runner.os != 'Windows'
        uses: actions/cache@v1
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-r-${{ matrix.config.r }}-1-${{ hashFiles('.github/depends.Rds') }}
          restore-keys: ${{ runner.os }}-r-${{ matrix.config.r }}-1-

      - name: Install system dependencies
        if: runner.os == 'Linux'
        run: |
          while read -r cmd
          do
            eval sudo $cmd
          done < <(Rscript -e 'cat(remotes::system_requirements("ubuntu", "16.04"), sep = "\n")')


      - name: Install dependencies
        #if: runner.os != 'Windows'
        run: |
          remotes::install_deps(dependencies = TRUE)
          remotes::install_github("Dschaykib/newsmd")
          remotes::install_cran("rcmdcheck")
        shell: Rscript {0}

      # newer source versions are available for some packages,
      # but compilation fails on Windows machines (RTools is missing).
      # therefore, force installation of binaries for *all* packages on Windows.
      # - name: Install only binaries on Windows (RTools missing)
      #   if: runner.os == 'Windows'
      #   run: remotes::install_deps(dependencies = TRUE, type = 'binary')
      #   shell: Rscript {0}


      - name: Session info
        run: |
          options(width = 100)
          installed.packages()[,c("Version","Built")]
        shell: Rscript {0}

      - name: Check
        env:
          _R_CHECK_CRAN_INCOMING_: FALSE
        run: rcmdcheck::rcmdcheck(args = c("--as-cran", "--no-manual", "--no-build-vignettes"), error_on = "warning", check_dir = "check")
        shell: Rscript {0}

      - name: Upload check results
        if: failure()
        uses: actions/upload-artifact@master
        with:
          name: ${{ runner.os }}-r${{ matrix.config.r }}-results
          path: check