on:
  pull_request:
    branches:
      - master
name: R-CMD-check-fix

jobs:
  R-CMD-check-fix:
    runs-on: ${{ matrix.config.os }}
    name: ${{ matrix.config.os }} (${{ matrix.config.r }})
    if: "!contains(github.event.head_commit.message, 'skip ci')"

    strategy:
      fail-fast: false
      matrix:
        config:
          # WINDOWS
          - {os: windows-latest, r: '3.6'}
          - {os: windows-latest, r: '4.0'}
          - {os: windows-latest, r: '4.2'}
          # MAC
          - {os: macOS-latest, r: '3.6'}
          - {os: macOS-latest, r: '4.0'}
          - {os: macOS-latest, r: '4.2'}
          # LINUX
          - {os: ubuntu-latest, r: '3.6'}
          - {os: ubuntu-latest, r: '4.0'}
          - {os: ubuntu-latest, r: '4.2'}


    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true

      - name: Session info
        run: version
        shell: Rscript {0}

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck
          needs: check

      - uses: r-lib/actions/check-r-package@v2
        with:
          upload-snapshots: true