on: [push, pull_request]
name: test-coverage

jobs:
  test-coverage:
    runs-on: macOS-latest
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@master

      - uses: r-lib/actions/setup-pandoc@master

      - name: Query dependencies
        run: |
          install.packages('remotes')
        shell: Rscript {0}

      #- name: Cache R packages
      #  uses: actions/cache@v1
      #  with:
      #    path: ${{ env.R_LIBS_USER }}
      #    key: macOS-r-4.0-1-${{ hashFiles('.github/depends.Rds') }}
      #    restore-keys: macOS-r-4.0-1-

      - name: Install dependencies
        run: |
          remotes::install_deps(dependencies = TRUE)
          remotes::install_cran("covr")
        shell: Rscript {0}

      - name: Test coverage
        run: covr::codecov()
        shell: Rscript {0}
